### ISSUE TITLE
Checklist for Participant Class

### ISSUE THREAD

**Issue by bcorrie** [airr-knowledge/issues#24]
- [x] Is the class an entity or a process? Is it an information entity about a material entity/process, or a pure information entity/process?

Entity

- [x] Specify the ontology URI for class. Is there a hierarchy of ontology terms that are relevant?

See Google Sheet

- [x] Define the slots for the class. Every slot should have an URI either to an ontology term or schema.org term for its semantics. Is there a hierarchy of terms that are relevant for its semantics?

See Google Sheet

- [x] Define the attributes of each slot. Identifier? Required? Data type? Controlled vocabulary or ontology for the values?

See Google Sheet

- [x] Define the direct relations to other objects. What is the cardinality of the relation? Is there an ontology URI for the relation?

See Google Sheet

- [x] If the class is a process, there should be slots for the inputs/outputs of the process. They may be directly defined in the class or are relations.

Not a process

- [x] Should any slots be potential made into a class? Is the class a composite of other classes?

I believe that the class should be called ParticpantOrganism and it should have two subclasses, ParticipantHuman and ParticipantNonHuman

Slots for Class and Subclasses laid out in Google Sheet.

- [x] Review and approval by each group (ADC, IEDB, IRAD, OGRDB)

**Comment by schristley** [comment]
> * [ ]  Is the class an entity or a process? Is it an information entity about a material entity/process, or a pure information entity/process?

Participant is an entity. It is an information entity about a material entity.

**Comment by bcorrie** [comment]
> * [ ]  Specify the ontology URI for class. Is there a hierarchy of ontology terms that are relevant?

http://purl.obolibrary.org/obo/OBI_0000097

**Comment by bcorrie** [comment]
@schristley @jamesaoverton before I go down a rabbit hole on this, since I believe the fields/slots for `Particpant` that we are starting with came from IEDB, I suspect that IEDB has URI's that would cover these slots??? It doesn't make a lot of sense for me to start from scratch on these. For example, I am sure there is an accepted ontology for `biological_sex`?

@jamesaoverton I am happy to copy and paste things in from an IEDB spec/definition, so I can save you that work if you can point me to such a thing...

**Comment by jamesaoverton** [comment]
@bcorrie Yes, we have a lot of these mappings from previous work, and we're happy to help. I'll make a public document.

For 'biological sex' we prefer PATO 'genotypic sex' http://purl.obolibrary.org/obo/PATO_0020000. For 'participant' we probably want OBI 'organism' http://purl.obolibrary.org/obo/OBI_0100026, or maybe something more specific.

**Comment by bcorrie** [comment]
I have been looking around at both LinkML and projects that use LinkML. This seems similar to our `Particpant` and uses LinkML under the hood presumably.

https://cancerdhc.github.io/ccdhmodel/v1.2/Subject/

I found the link to the Cancer Research Data Commons on the LinkML site:

https://linkml.io/linkml/examples.html#introductory-example

Turns out it isn't really helpful other than to confirm that our fields are not ridiculous - but we knew that.

So they have this nice Class/Entity model with relationships, but as far as I can tell they have no links to external definitions of any kind (no external URIs are used) and they define everything internally with enums. Am I missing something? I have to say LinkML thus far as confused me more than helped.

**Comment by bcorrie** [comment]
So far this has been the best link I have found that explains how LinkML works in a practical sense:

https://biolink.github.io/biolink-model/using-the-modeling-language/

**Comment by schristley** [comment]
@bcorrie How helpful would it before for you if you can enter LinkML and then view the corresponding JSON schema? If you think that will help then I can send some instructions for playing with ak-schema. It is relatively straightforward with using docker.

I should have instructions in the README but I've not gotten past just creating the base repo.

**Comment by bcorrie** [comment]
@schristley I think we should work through a couple of concrete examples like the `Participant` class and its fields - we being you, @jamesaoverton and I, and create a "complete" definition in the sense of coming up with and agreeing on what the columns in the spreadsheet should be and what the resultant LinkML object would look like.  You are the project lead (you know what you want), James is the ontology expert, and I am the team member is tasked with the job. I think if we have a "finished" class as concrete example of what is being looked for then the rest of the group will be able to move forward much more easily on the other classes.

I suggest `Participant` because I think it is about as simple a class as we have, with fields that I think should have clear definitions for what the field means (field definition) as well as well defined ontologies for what the values of the field should be able to take on (the range).

I think this is important, as when I look at a field like `Participant.biological_sex` I am still not clear what I should be doing 8-). If we are going to use this approach, it should be fairly trivial for me to deal with this field - and yet it isn't.

**Comment by bcorrie** [comment]
To be honest, LinkML is confusing me to no end. Why, oh why, does it have to use different terms for things (slots - really?).

And why do they overload the term "slot". 

- On the one hand, a slot is the same "... as fields in traditional object languages": https://linkml.io/linkml/schemas/slots.html - why did they not use field then?
- On the other hand, slots are used to capture other concepts like inheritance, using "metamodel slots": https://linkml.io/linkml/schemas/inheritance.html

Basically everything in LinkML is a slot as far as I can tell...

Coming at this fresh from the outside, this makes their terminology a mess and their documentation confusing, at least to my tired old brain...

**Comment by bcorrie** [comment]
Fundamentally this class is simple (from here):

```
classes:
  Participant:
    is_a: MaterialEntity ## parent class
    description: >-
      A participant in a study
    class_uri: schema:Person ##???
    slots:
      - participant_id
      - biological_sex
      - race
      - race_specify
      - ethnicity
      - geolocation
```
Call me done...

**Comment by bcorrie** [comment]
But what we really want is:

```
prefixes:
  OBI: http://purl.obolibrary.org/obo/OBI_
  IAO: http://purl.obolibrary.org/obo/IAO_
  NCIT: http://purl.obolibrary.org/obo/NCIT_
  PATO: http://purl.obolibrary.org/obo/PATO_

classes:
  Participant:
    is_a: MaterialEntity ## parent class
    description: >-
      A participant in a study
    class_uri: OBI:0000026
    attributes:
       participant_id:
         identifier: true
         slot_uri: IA0:0020000
         range: *
      biological_sex:
         slot_uri: PATO:0000047
         range: NCIT:C28421
      race:
         slot_uri: ???
         range: ???
      race_specify:
         slot_uri: ???
         range: ???
      ethnicity:
         slot_uri: ???
         range: ???
      geolocation:
         slot_uri: ???
         range: ???
```
Where I think each of the question marks in the above should be replaced by a value from a column in the object spreadsheet...

I have matched up the spreadsheet with the above for `Participant.biological_sex`.

**Comment by schristley** [comment]
> > * [ ]   Specify the ontology URI for class. Is there a hierarchy of ontology terms that are relevant?
> 
> http://purl.obolibrary.org/obo/OBI_0000097

This term is actually about the role of the participant versus the material entity. I would go with organism as suggested by James.

http://purl.obolibrary.org/obo/OBI_0100026

```
    class_uri: OBI:0100026
```

**Comment by schristley** [comment]
> So they have this nice Class/Entity model with relationships, but as far as I can tell they have no links to external definitions of any kind (no external URIs are used) and they define everything internally with enums. Am I missing something? I have to say LinkML thus far as confused me more than helped.

I was confused about that as well as it seemed like all the enums where hard-coded controlled vocabulary. But then I found this [Dynamic Enum](https://linkml.io/linkml/schemas/enums.html#dynamic-enums). It is similar to how we coded this in the AIRR standards, specify 1) ontology (`source_ontology`) and 2) the root term (`source_nodes`). Though it looks more advanced in that you can specify multiple ontologies and exclude parts of the ontology tree.

**Comment by bcorrie** [comment]
> I was confused about that as well as it seemed like all the enums where hard-coded controlled vocabulary. But then I found this [Dynamic Enum](https://linkml.io/linkml/schemas/enums.html#dynamic-enums). It is similar to how we coded this in the AIRR standards, specify 1) ontology (`source_ontology`) and 2) the root term (`source_nodes`). Though it looks more advanced in that you can specify multiple ontologies and exclude parts of the ontology tree.

That is cool, but as far as I can tell Cancer Research Data Commons does not use that, they have encoded everything as Static Enums (https://cancerdhc.github.io/ccdhmodel/v1.2/#enums). Admittedly it looks like many of them are autogenerated from some other source (which I can't find). So maybe this predates the DynamicEnum?

**Comment by schristley** [comment]
> Fundamentally this class is simple (from here): https://linkml.io/linkml/intro/overview.html
> 
> ```
> classes:
>   Participant:
>     is_a: MaterialEntity ## parent class
>     description: >-
>       An organism that is a participant in a study
>     class_uri: OBI:0100026
>     slots:
>       - participant_id
>       - biological_sex
>       - race
>       - race_specify
>       - ethnicity
>       - geolocation
> ```
> 
> Call me done...

Yep, that is good enough. The slots can be defined in each class or globally in the slots object. I would initially going with global slots in case we want to re-use them on other classes. Then iniitially give them simple ranges as Type.

```
slots:
  biological_sex:
    range: string
  race:
    range: string
  ethnicity:
    range: string
  geolocation:
    range: string
```

**Comment by schristley** [comment]
In the AIRR spec, `biological_sex` is a controlled vocabulary enum, and both `race` and `ethnicity` are just strings. In AIRR, `geolocation` is in an ontology so let's add that in:

```
                    top_node:
                        id: GAZ:00000448
                        label: geographic location
```

Change the range to be an enum

```
slots:
  geolocation:
    range: GeoLocationEnum
```

Now define the enumeration. Unfortunately the doc doesn't do a good job of explaining what that the different properties so I'm just copy/pasting

```
enums:
  GeoLocationEnum:
      source_ontology: OBO:GAZ
      source_nodes:
        - GAZ:00000448
      include_self: false
      relationship_types:
        - rdfs:subClassOf
```

**Comment by schristley** [comment]
However, note that we are being a bit imprecise. The `class_uri: OBI:0100026` is a more generic organism while our `Participant` implies a human. So we'll likely want to create a hierarchy of classes, so we can subclasses with specialized slots.

```
classes:
  Organism:
    is_a: MaterialEntity ## parent class
    description: >-
      An organism that is a participant in a study
    class_uri: OBI:0100026
    slots:
      - organism_id
      - biological_sex
      - geolocation

  HumanParticipant:
    is_a: Organism
    slots:
      - race
      - race_specify
      - ethnicity

  MouseParticipant:
    is_a: Organism
    slots:
    - strain_name

```
We'll need to discuss this a bit to make sure we are doing the right thing though. I imagine like with OO programming, sometimes you want to create a subclass and other times you just want a `organism_type` to handle variations...
